kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.applicationName }}-https
  labels:
    app: {{ .Values.applicationName }}
  annotations:
    description: Route for application's default https service.
spec:
  to:
    name: {{ .Values.applicationName }}
    kind: Service
  tls:
    termination: edge
